// <auto-generated />
using ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Migrations
{
    [DbContext(typeof(MVCContext))]
    [Migration("20231119150804_Utworzenie")]
    partial class Utworzenie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models.Miasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Populacja")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Miasta");
                });
#pragma warning restore 612, 618
        }
    }
}
